### ISSUE TITLE
Lock and Unlock missing from URIBeacon2Service.h

### ISSUE THREAD

**Issue by schilit** [mbedmicro/BLE_API#10]
Hi @rgrover 

[Lock](https://github.com/google/uribeacon/blob/master/specification/ConfigService.md#31-lock-state) and [Unlock](https://github.com/google/uribeacon/blob/master/specification/ConfigService.md#33-unlock) are missing from URIBeacon2Service.h

The Lock value should be stored in non-volatile memory. Lock value can be set to 0 to indicate unlocked, therefore Lock State can be based solely on Lock value.

A phone initiates a GATT connection, reads all characteristics including lock state. If updates are necessary it will check lock state and issue: unlock*, write+, lock* (* optional).

The type is defined as `uint128` but we are considering making `uint8[]` of any size. Let us know if you have a strong opinion on this.

**Comment by rgrover** [comment]
fixed with release 0.2.10 of BLE_API (https://github.com/mbedmicro/BLE_API/commit/540c8c2ba7bc861558fcec77c8c15bc40002624d), and with the corresponding commit to nRF51822 (https://github.com/mbedmicro/nRF51822/commit/e4fab54bf2527083fef2fdeb13079e68a5d4e0f9)

Also updated mercurial repositories on mbed.org. You should be able to build from mbed.org's online compiler directly.
http://developer.mbed.org/teams/Bluetooth-Low-Energy/code/BLE_URIBeacon/
